// <auto-generated />
namespace Clinic_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addrate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrate));
        
        string IMigrationMetadata.Id
        {
            get { return "202008051337115_add rate "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
